### ISSUE TITLE
SIGSEGV on update

### ISSUE THREAD

**Issue by hangxie** [jsonnet-bundler/jsonnet-bundler#118]
yet to determine the root cause as it happens on my colleague's laptop with 0.3.1, we may provide more details tomorrow once have time to setup a triage session (or not):
```
 * [new tag]         v0.8.0     -> v0.8.0
 * [new tag]         v0.9.0     -> v0.9.0
HEAD is now at d9f11a2 Add modules from random provider
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x773ff2]

goroutine 1 [running]:
github.com/jsonnet-bundler/jsonnet-bundler/pkg.Ensure.func1(0xc0004c2410, 0x4e, 0x0, 0x0, 0x8d98a0, 0xc0004e48a0, 0x0, 0x0)
	/home/vagrant/x/pkg/mod/github.com/jsonnet-bundler/jsonnet-bundler@v0.3.1/pkg/packages.go:69 +0x42
path/filepath.walk(0xc00001f7c0, 0x3a, 0x8e2980, 0xc0001a15f0, 0xc00069ba40, 0x0, 0x0)
	/usr/local/go/src/path/filepath/path.go:378 +0x20c
path/filepath.walk(0xc00001f700, 0x32, 0x8e2980, 0xc0001a1520, 0xc00069ba40, 0x0, 0x0)
	/usr/local/go/src/path/filepath/path.go:382 +0x2ff
path/filepath.walk(0xc0003f8e60, 0x20, 0x8e2980, 0xc0000f5930, 0xc00069ba40, 0x0, 0x0)
	/usr/local/go/src/path/filepath/path.go:382 +0x2ff
path/filepath.walk(0xc0003f8da0, 0x1c, 0x8e2980, 0xc0000f5860, 0xc00069ba40, 0x0, 0x0)
	/usr/local/go/src/path/filepath/path.go:382 +0x2ff
path/filepath.walk(0x84f5f3, 0x6, 0x8e2980, 0xc0000f5110, 0xc00069ba40, 0x0, 0x0)
	/usr/local/go/src/path/filepath/path.go:382 +0x2ff
path/filepath.Walk(0x84f5f3, 0x6, 0xc00069ba40, 0xc00069bb68, 0xc00010ced0)
	/usr/local/go/src/path/filepath/path.go:404 +0xff
github.com/jsonnet-bundler/jsonnet-bundler/pkg.Ensure(0xc00010ce40, 0x0, 0x84f5f3, 0x6, 0xc00014fb68, 0x0, 0x0, 0x0)
	/home/vagrant/x/pkg/mod/github.com/jsonnet-bundler/jsonnet-bundler@v0.3.1/pkg/packages.go:65 +0x10f
main.updateCommand(0xc00001a074, 0x5f, 0x84f5f3, 0x6, 0x0, 0x0, 0x0, 0x0)
	/home/vagrant/x/pkg/mod/github.com/jsonnet-bundler/jsonnet-bundler@v0.3.1/cmd/jb/update.go:44 +0x300
main.Main(0xc00007e058)
	/home/vagrant/x/pkg/mod/github.com/jsonnet-bundler/jsonnet-bundler@v0.3.1/cmd/jb/main.go:79 +0x7d2
main.main()
	/home/vagrant/x/pkg/mod/github.com/jsonnet-bundler/jsonnet-bundler@v0.3.1/cmd/jb/main.go:34 +0x22
make: *** [../../common/makefiles/common.mk:54: vendor] Error 2
```

It seems https://github.com/jsonnet-bundler/jsonnet-bundler/blob/v0.3.1/pkg/packages.go#L65-L71 should check error to take proper action (reporting offending file?) instead of blindly check `!i.IsDir()` as `i` will be `nil` if callback of `filepath.Walk` gets an error.

**Comment by metalmatze** [comment]
We checked a bunch of these issues on newer 0.4.x releases. Can you upgrade?

**Comment by hangxie** [comment]
> Can you upgrade?

Yes that's one of the action item but may take a while (there are like ~20 some people in 2 dev teams)

FYI, the test environment was gone, we assume it was triggered by underlying file system problem - Josh was running a vagrant-based dev env with directory mounted into the VM, he's the only one had this problem though there are couple of other people have the same setup. Josh then moved to container based dev env and everything works just fine.

I'm going to close this as it's no longer an issue.
