### ISSUE TITLE
panic during `jb install` over ssh

### ISSUE THREAD

**Issue by ghostsquad** [jsonnet-bundler/jsonnet-bundler#119]
```
jb install git+ssh://git@github.com/my-org/spinnaker-libsonnet.git@70d5d07eb7a506030079372243178a87483d0a68
Initialized empty Git repository in /Users/wmcnamee/projects/test-proj/vendor/.tmp/jsonnetpkg-github.com-my-org-spinnaker-libsonnet-70d5d07eb7a506030079372243178a87483d0a68979173229/.git/
remote: Enumerating objects: 8, done.
remote: Counting objects: 100% (8/8), done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 8 (delta 1), reused 8 (delta 1), pack-reused 0
Unpacking objects: 100% (8/8), 4.48 KiB | 763.00 KiB/s, done.
From ssh://github.com/my-org/spinnaker-libsonnet
 * branch            70d5d07eb7a506030079372243178a87483d0a68 -> FETCH_HEAD
HEAD is now at 70d5d07 feat: 🎉  initial commit
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x11e6ccb]

goroutine 1 [running]:
github.com/jsonnet-bundler/jsonnet-bundler/spec/v1.FromV0(0xc0000126c0, 0xeb, 0x2eb, 0x13cd720, 0xc000010198)
	/Users/wmcnamee/go/pkg/mod/github.com/jsonnet-bundler/jsonnet-bundler@v0.4.0/spec/v1/v0.go:32 +0x2fb
github.com/jsonnet-bundler/jsonnet-bundler/pkg/jsonnetfile.Unmarshal(0xc0000fe000, 0xeb, 0x2eb, 0xeb, 0x2eb, 0x0, 0x0)
	/Users/wmcnamee/go/pkg/mod/github.com/jsonnet-bundler/jsonnet-bundler@v0.4.0/pkg/jsonnetfile/jsonnetfile.go:71 +0x2c5
github.com/jsonnet-bundler/jsonnet-bundler/pkg/jsonnetfile.Load(0xc0000264d0, 0x61, 0x3, 0xc0000264d0, 0x61, 0x0)
	/Users/wmcnamee/go/pkg/mod/github.com/jsonnet-bundler/jsonnet-bundler@v0.4.0/pkg/jsonnetfile/jsonnetfile.go:44 +0xa8
github.com/jsonnet-bundler/jsonnet-bundler/pkg.ensure(0xc00011bf50, 0xc0001361e0, 0x2a, 0xc00011bfb0, 0x2a, 0x0, 0x1)
	/Users/wmcnamee/go/pkg/mod/github.com/jsonnet-bundler/jsonnet-bundler@v0.4.0/pkg/packages.go:251 +0xe3b
github.com/jsonnet-bundler/jsonnet-bundler/pkg.Ensure(0xc00011bf50, 0x1, 0xc0001361e0, 0x2a, 0xc00011bfb0, 0x0, 0x0, 0x0)
	/Users/wmcnamee/go/pkg/mod/github.com/jsonnet-bundler/jsonnet-bundler@v0.4.0/pkg/packages.go:55 +0x67
main.installCommand(0xc00001e004, 0x23, 0x1436487, 0x6, 0xc000118fc0, 0x1, 0x1, 0x0, 0x0)
	/Users/wmcnamee/go/pkg/mod/github.com/jsonnet-bundler/jsonnet-bundler@v0.4.0/cmd/jb/install.go:76 +0x74c
main.Main(0xc00010e058)
	/Users/wmcnamee/go/pkg/mod/github.com/jsonnet-bundler/jsonnet-bundler@v0.4.0/cmd/jb/main.go:82 +0xb07
main.main()
	/Users/wmcnamee/go/pkg/mod/github.com/jsonnet-bundler/jsonnet-bundler@v0.4.0/cmd/jb/main.go:37 +0x22
```

**Comment by ghostsquad** [comment]
Oh, this is an incompatibility of `jsonnetfile.json` it seems prior to `0.4.0`. Since I'm in control of the upstream in this case, I was able to delete/recreate the files with a newer version of `jb`

**Comment by ghostsquad** [comment]
```diff
jsonnetfile.json
  
   {
     "version": 1,
     "dependencies": [
       {
+        "name": "util-libsonnet",
         "source": {
           "git": {
-            "remote": "ssh://git@github.com/my-org/util-libsonnet.git",
+            "remote": "git@github.com:my-org/util-libsonnet",
             "subdir": ""
           }
         },
         "version": "master"
       }
-    ],
-    "legacyImports": true
+    ]
   }
```

**Comment by ghostsquad** [comment]
this apparently doesn't work either for non-master branches, see #130
