### ISSUE TITLE
Panic on `jb install` due to permission denied

### ISSUE THREAD

**Issue by sarahhodne** [jsonnet-bundler/jsonnet-bundler#96]
I'm getting a panic when trying to run `jb install`:

```
$ jb install github.com/coreos/kube-prometheus/jsonnet/kube-prometheus@release-0.4
GET https://github.com/coreos/kube-prometheus/archive/ee8077db04965d6b4d9e6a328d5283dd6ba71d33.tar.gz 200
panic: rename vendor/.tmp/jsonnetpkg-github.com-coreos-kube-prometheus-jsonnet-kube-prometheus-release-0.4678299929/jsonnet/kube-prometheus vendor/github.com/coreos/kube-prometheus/jsonnet/kube-prometheus: permission denied

goroutine 1 [running]:
github.com/jsonnet-bundler/jsonnet-bundler/pkg.(*GitPackage).Install(0xc0000b2268, 0x8e0ce0, 0xc0000ae038, 0xc0000d4840, 0x39, 0x84f5f3, 0x6, 0x7fffc9faddbc, 0xb, 0x0, ...)
        /home/sarah/go/pkg/mod/github.com/jsonnet-bundler/jsonnet-bundler@v0.3.1/pkg/git.go:212 +0x24ac
github.com/jsonnet-bundler/jsonnet-bundler/pkg.download(0xc0000d6370, 0x0, 0x7fffc9faddbc, 0xb, 0x0, 0x0, 0x0, 0x0, 0x84f5f3, 0x6, ...)
        /home/sarah/go/pkg/mod/github.com/jsonnet-bundler/jsonnet-bundler@v0.3.1/pkg/packages.go:284 +0x192
github.com/jsonnet-bundler/jsonnet-bundler/pkg.ensure(0xc0001140c0, 0x84f5f3, 0x6, 0xc000114120, 0xc000099040, 0xc000157ad8, 0x5e9042)
        /home/sarah/go/pkg/mod/github.com/jsonnet-bundler/jsonnet-bundler@v0.3.1/pkg/packages.go:233 +0x60e
github.com/jsonnet-bundler/jsonnet-bundler/pkg.Ensure(0xc0001140c0, 0xc000114101, 0x84f5f3, 0x6, 0xc000114120, 0x0, 0x0, 0x0)
        /home/sarah/go/pkg/mod/github.com/jsonnet-bundler/jsonnet-bundler@v0.3.1/pkg/packages.go:55 +0x67
main.installCommand(0xc00001e004, 0x2d, 0x84f5f3, 0x6, 0xc000094ee0, 0x1, 0x1, 0x0)
        /home/sarah/go/pkg/mod/github.com/jsonnet-bundler/jsonnet-bundler@v0.3.1/cmd/jb/install.go:71 +0x68b
main.Main(0xc00008a058)
        /home/sarah/go/pkg/mod/github.com/jsonnet-bundler/jsonnet-bundler@v0.3.1/cmd/jb/main.go:77 +0x860
main.main()
        /home/sarah/go/pkg/mod/github.com/jsonnet-bundler/jsonnet-bundler@v0.3.1/cmd/jb/main.go:34 +0x22
```

```
$ jb --version
v0.3.1
$ go version
go version go1.13.5 linux/amd64
$ git --version
git version 2.17.1
```

```
$ ls -Rla vendor/
vendor/:
total 0
drwxr-xr-x 1 sarah sarah 512 Apr 11 17:47 .
drwxrwxrwx 1 sarah sarah 512 Apr 11 17:47 ..
drwxr-xr-x 1 sarah sarah 512 Apr 11 17:51 .tmp
drwxr-xr-x 1 sarah sarah 512 Apr 11 17:47 github.com

vendor/.tmp:
total 0
drwxr-xr-x 1 sarah sarah 512 Apr 11 17:51 .
drwxr-xr-x 1 sarah sarah 512 Apr 11 17:47 ..

vendor/github.com:
total 0
drwxr-xr-x 1 sarah sarah 512 Apr 11 17:47 .
drwxr-xr-x 1 sarah sarah 512 Apr 11 17:47 ..
drwxr-xr-x 1 sarah sarah 512 Apr 11 17:47 coreos

vendor/github.com/coreos:
total 0
drwxr-xr-x 1 sarah sarah 512 Apr 11 17:47 .
drwxr-xr-x 1 sarah sarah 512 Apr 11 17:47 ..
drwxr-xr-x 1 sarah sarah 512 Apr 11 17:47 kube-prometheus

vendor/github.com/coreos/kube-prometheus:
total 0
drwxr-xr-x 1 sarah sarah 512 Apr 11 17:47 .
drwxr-xr-x 1 sarah sarah 512 Apr 11 17:47 ..
drwxr-xr-x 1 sarah sarah 512 Apr 11 17:47 jsonnet

vendor/github.com/coreos/kube-prometheus/jsonnet:
total 0
drwxr-xr-x 1 sarah sarah 512 Apr 11 17:47 .
drwxr-xr-x 1 sarah sarah 512 Apr 11 17:47 ..
```

I am using WSL, so it's possible that there's some weird interaction there? Otherwise I'm not sure what could be causing permissions errors...

**Comment by sh0rez** [comment]
Huh, this seems odd. Just confirmed, it works on macOS and a regular linux node, so it's related to your setup.

Do you run wsl2 or the older one? Please post `uname -a`

**Comment by sarahhodne** [comment]
The old WSL, I believe (last I checked, WSL2 was only in the insider builds?)

```
$ uname -a
Linux strax 4.4.0-18362-Microsoft #476-Microsoft Fri Nov 01 16:53:00 PST 2019 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by sh0rez** [comment]
Yeah, seems to wsl1. I know there is an issue when inotify is in use which prevents you from saving files then, but jb doesn't do this. 

Is there anything watching this directory tree? (vscode, etc)?

**Comment by davidovich** [comment]
I suspect the OP is using VSCode with WSL, which has a known limitation
that I encountered too. The solution is to turn off file watching.

More info here:
https://code.visualstudio.com/docs/remote/wsl#_known-limitations

D.

**Comment by sh0rez** [comment]
@sarahhodne could you check the suggestion by @davidovich?

**Comment by sarahhodne** [comment]
Ah, yeah, it looks like it was Visual Studio code indeed, I didn't try turning off file watching yet, but I can't reproduce it when I quit VS Code, so I am pretty confident that that's the reason.
